### ISSUE TITLE
Should a failed patch trigger the plugin's execution to fail?

### ISSUE THREAD

**Issue by paulmillar** [LukasMansour/patch-maven-plugin#1]
Hi Lukas,

If I've understood correctly, the plugin has the following behaviour:  if one of the patches fails to apply (to one of its files) then a warning is logged and the subsequent files of the patch (if any) are skipped.  However, this doesn't seem to trigger a failure in the overall execution.

(Again, if I've understood correctly, then ...)  Under these circumstances, maven would continue the build.

Building a project with partially applied patches might lead to some rather weird errors.  The risk being that it would take non-trivial time to track down what went wrong.

Personally, I think a better strategy would be that the plugin's execution would fail (and so, failing the maven build) should any patch not apply.

Cheers,
Paul.

**Comment by LukasMansour** [comment]
Hi Paul,

I agree that it is an oversight, that it continues to apply patches. So if patch '1' doesn't apply, An update will prevent patch '2' from applying. One could if really necessary event revert patches (let me know if you think this is necessary), This should prevent the 'partially applied patches' from occurring.

However, failing the building is problematic, as in contrary to git, we don't have a 'permanent stash' to keep track of which patches are already applied. That means that running the patch plugin twice, would result in a failure, since it would be patching an already patched file, hence leading to conflicts.

I could add a flag to 'failOnFailedPatch' but I believe you can see the issue as you no longer know if the patch failed due to changes or if it failed due to already being applied. Maybe there is some clever checksum logic, but I haven't worked it out yet.

Cheers,
Lukas

**Comment by paulmillar** [comment]
Hi Lukas,

If I've understood the code correctly, if the desired changes to some file (within a patch) fail to apply then an execution will only skips further file-changes (if any) within this problematic patch.  The remaining patches (if any) would still be applied.

Personally, I'd prefer any failure to apply a patch resulted in the build failing.  I think logging a warning, while certainly helpful, isn't enough when this plugin is used in more extensive maven builds.

I agree: a patch not applying would be a difficult situation from which to recover, if one wishes to continue applying patches.  However, I would think that simply running the maven `clean` target would provide an easy recovery path.

So, if it's not too difficult, I'd be grateful if you could add a `failOnFailedPatch` flag/option, to cover this case.

Cheers,
Paul.

**Comment by LukasMansour** [comment]
Hi Paul,

agreed, then let me list the things that I will change in the coming version 1.1.0 according to your issue:
- Only write the diffs to the filesystem, if the entire patch could be applied (do not apply half a patch).
- Add a 'failOnFailedPatch' flag. Which will fail the plugin if a patch could not be fully applied.

Standard behaviour if the 'failOnFailedPatch' is false, would be: Post a warning for the patch, and move onto the next patch.

Perhaps in the dCache building I would recommend coupling the srm-common:clean task with the patch:apply execution, otherwise it may be annoying running 'mvn package' and failing 'sporadically'. This would be a great way to handle it is to always by default clean srm-common, the other modules don't have to be cleaned, improving compilation time.

Let me know if I have forgotten anything or if anything is unclear,

Cheers,
Lukas

**Comment by paulmillar** [comment]
Hi Lukas,

> coupling the srm-common:clean task with the patch:apply execution

Perhaps; however, I don't think this should be necessary.  To me, this sounds like a work-around for some other (underlying) issue.  However, we can always revisit this, if it really turns out to be a problem.

> Let me know if I have forgotten anything or if anything is unclear,

I think the changes you describe sound good.

Cheers,
Paul.

**Comment by LukasMansour** [comment]
Please pull the project and build the version 1.1.0-SNAPSHOT and have a look if it matches your expectations,
make sure to set the 'failOnFailedPatch' flag to 'true'.

In whatever way you add this to dCache's building, I haven't worked out a reasonable checksumming/verification scheme for it to just apply patches on 'unpatched' files. (You run into a sort of chicken and an egg problem).

Hence, I really do recommend either not failing (failOnFailedPatch = 'false'), or for the 'srm-common' always applying the maven-clean-plugin beforehand. Otherwise, with the expected behaviour above, it will fail on every second sequential call of 'mvn package' and making a developer manually clean, seems like a very annoying work-around.

I am working on a snapshot-repository for snapshot deployment, but haven't got it working it yet, hence you will have to build the artifact yourself I'm afraid, it should as simple as running 'gradlew publishToMavenLocal'

Cheers,
Lukas

**Comment by paulmillar** [comment]
Yup, the update looks good to me.  Thanks for the quick response.
